# Generated by Django 5.0.4 on 2024-06-02 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre Estudiante')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre Profesor')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Proyecto')),
                ('tipo', models.CharField(choices=[('0', 'Tipo 1'), ('1', 'Tipo 2'), ('2', 'Tipo 3'), ('3', 'Tipo 4')], max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
        ),
    ]
