# Generated by Django 5.0.4 on 2024-06-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proyecto_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estudiante',
            field=models.CharField(max_length=25, verbose_name='Nombre Estudiante'),
        ),
    ]
