# Generated by Django 5.0.4 on 2024-06-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_proyecto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.profesor'),
        ),
    ]
