# Generated by Django 5.0.4 on 2024-06-03 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_proyecto_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor'),
        ),
    ]
